apiVersion: argoproj.io/v1alpha1
kind: Rollout

metadata:
  name: hotstar
  namespace: hotstar
  labels:
    app: hotstar

spec:
  replicas: 3

  selector:
    matchLabels:
      app: hotstar

  template:
    metadata:
      labels:
        app: hotstar

    spec:
      containers:
        - name: hotstar
          image: rajeshpalei/hotstar:latest

          ports:
            - containerPort: 8080

          resources:
            requests:
              memory: "124Mi"
            limits:
              memory: "128Mi"

  strategy:
    blueGreen:
      activeService: hotstar-active
      previewService: hotstar-preview
      autoPromotionEnabled: false
